server:
  port: 8000

spring:
    application:
      name: user_service
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
      driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
      url: jdbc:mysql://localhost:3306/user              # 数据库名称
      username: root
      password: 123456
      dbcp2:
        min-idle: 5                                           # 数据库连接池的最小维持连接数
        initial-size: 5                                       # 初始化连接数
        max-total: 5                                          # 最大连接数
        max-wait-millis: 200                                  # 等待连接获取的最大超时时间

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #按字段名字建表
        show-sql: true
        database: mysql
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    thymeleaf:
      prefix: templats
      mode: HTML5

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://192.168.123.131:7001/eureka
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    instance:
      instance-id: user_service
      prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: user_service
  company.name: www.ant.cc
  build.artifactId: $project.artifactId$
  build.version: $project.version$
